// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzBjMHrra7a4Q-owXZjqYH-oFaL7_C9JA',
    appId: '1:698918366401:android:19acd1ea4ce11b29073840',
    messagingSenderId: '698918366401',
    projectId: 'chatapp-255d6',
    storageBucket: 'chatapp-255d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPd-saQnJvg-DiDvHw8-RMq0IebsRXJKg',
    appId: '1:698918366401:ios:4444964f1b720ef5073840',
    messagingSenderId: '698918366401',
    projectId: 'chatapp-255d6',
    storageBucket: 'chatapp-255d6.appspot.com',
    iosBundleId: 'com.dymmyapps.chatapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG-n20NQgQ9FczwzaYDDNzmHQsJD5JGEY',
    appId: '1:698918366401:web:67609ee85f452b5d073840',
    messagingSenderId: '698918366401',
    projectId: 'chatapp-255d6',
    authDomain: 'chatapp-255d6.firebaseapp.com',
    storageBucket: 'chatapp-255d6.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG-n20NQgQ9FczwzaYDDNzmHQsJD5JGEY',
    appId: '1:698918366401:web:8a05990f7c80c1e0073840',
    messagingSenderId: '698918366401',
    projectId: 'chatapp-255d6',
    authDomain: 'chatapp-255d6.firebaseapp.com',
    storageBucket: 'chatapp-255d6.appspot.com',
  );

}